### ISSUE TITLE
Confusing vertical spacing in “Integration” section

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-web-and-design/charmed-osm.com#11]
1\. Go to [charmed-osm.com](https://charmed-osm.com/)
2\. Scroll to the “Integration” section

What you see: The first section is much closer to the “Integration” heading than it is to the second section. This gives the appearance that “Integration” is a heading just for the first section, not for the whole of this block.

![charmed-osm](https://user-images.githubusercontent.com/19801137/69041328-3d5fb800-09e7-11ea-9d5b-550a1d3c6966.png)

(This is on a phone screen, but the issue is the same on a desktop.)

What you should see: some combination of
- more margin below “Integration”, and
- less margin above+below the horizontal rules, and maybe even
- a horizontal rule above “Any Kubernetes” as well.

**Comment by matthewpaulthomas** [comment]
@anasereijo thinks this is a Vanilla design issue. On the Vanilla site I can’t find any mention of `<hr class="p-separator">`, but I think it’s a reasonable choice for `p-separator`’s vertical margin (4em) to be equal to `p-strip`’s vertical padding. Perhaps they’re just not meant to be used one inside the other, or at least, not with an overarching heading.

The problem would not occur if using `<div class="is-bordered">`, like [the Kubernetes docs do](https://ubuntu.com/kubernetes/docs/openstack-integration) for example.

**Comment by lyubomir-popov** [comment]
This is not a vanilla issue, vanilla does provide alternatives, and the [pr](url) which closed this issue is not a recommended way of handling this sort of scenario. I've added 3 alternative ways to achieve the same on the pr.
